import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Footer from '../comps/footer'
import Navbar from '../comps/navbar'
import styles from '../styles/Home.module.css'
import { useSession } from 'next-auth/react'
import Link from 'next/link'
import { useState } from 'react'
const Home: NextPage = () => {
  const {data: session} = useSession()
  const user = session?.user?.name
  console.log(user)
  const [searchValue, setSearchValue] = useState('')
  let searched = `/order/${searchValue}`
  return (
    <div className={styles.container}>
      <Head>
        <title>FOOD-APP</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='container'>
        <Navbar />
        <div className='hero'>
          <div className="img-con">
            <Image src={'/hero.jpg'} alt='hero img' title='Erik Mclean - unsplash' layout='fill' />
          </div>
            <span className='hero-title'>WE ARE HERE TO MAKE YOUR LIFE EASIER!</span>
        </div>
        <div className='address-con'>
          <input className='search-input' onChange={(evt) => { setSearchValue(evt.target.value) }} placeholder='ENTER YOUR LOCATION... EG. WARSAW, PARIS'></input>
          <Link href={searched} className='button'>GO!</Link>
        </div>
        <div className='tuto'>
          <div className='first'>
            <span className='number'>1</span>
            <span className='text'>PICK YOUR LOCATION</span>
            <Image src={'/icons/location.png'} width='40px' height={'40px'}/>
          </div>
          <div className='sec'>
            <span className='number'>2</span>
            <span className='text'>SELECT YOUR FAVOURITE FOOD</span>
            <Image src={'/icons/fast-food.png'} width='40px' height={'40px'}/>
          </div>
          <div className='third'>
            <span className='number'>3</span>
            <span className='text'>PAY FOR IT</span>
            <Image src={'/icons/coin.png'} width='40px' height={'40px'}/>
          </div>
        </div>
        <Footer />
      </div>
    </div>
  )
}

export default Home
